"""
W3C PROV-O provenance document generator.

Produces a structured PROV document that captures the full audit trail of a
CHRONOS investigation: which agent ran it, what data it consumed, and what
report was generated — all expressed in W3C-standard provenance vocabulary.
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime

from prov.constants import PROV_TYPE
from prov.model import ProvDocument

from chronos.config.settings import settings

logger = logging.getLogger("chronos.compliance.prov")

CHRONOS_NS = "http://chronos.data/prov#"
PROV_NS = "http://www.w3.org/ns/prov#"


def _parse_iso_dt(value: str | None) -> datetime | None:
    """
    Parse an ISO-8601 datetime string, handling the 'Z' suffix and missing
    timezone info gracefully. Returns None on failure.
    """
    if not value:
        return None
    try:
        cleaned = value.replace("Z", "+00:00")
        dt = datetime.fromisoformat(cleaned)
        # Ensure the datetime is timezone-aware for PROV serialization
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=UTC)
        return dt
    except (ValueError, TypeError) as exc:
        logger.debug(f"Could not parse datetime '{value}': {exc}")
        return None


def _safe_id(raw: str) -> str:
    """Replace characters that are illegal in PROV identifiers."""
    return raw.replace(".", "_").replace(" ", "_").replace("/", "_").replace(":", "_")


def generate_provenance(incident_report: dict) -> ProvDocument:
    """
    Build a W3C PROV-O document for a completed investigation.

    The document captures:
    - The CHRONOS software agent
    - The investigation activity (start / end time)
    - The affected data asset (used by the activity)
    - The incident report entity (generated by the activity)
    - Each evidence item (used by and derived from)

    Supports serialization via ``prov_doc.serialize(format=...)``:
    - ``format="json"``  → JSON-LD
    - ``format="rdf", rdf_format="turtle"`` → Turtle RDF
    - ``format="provn"`` → PROV-N notation
    """
    d = ProvDocument()
    d.set_default_namespace(CHRONOS_NS)
    d.add_namespace("prov", PROV_NS)
    d.add_namespace("xsd", "http://www.w3.org/2001/XMLSchema#")
    d.add_namespace("chronos", CHRONOS_NS)

    incident_id = incident_report.get("incident_id", "unknown")
    entity_fqn = incident_report.get("affected_entity_fqn", "unknown")
    detected_at = _parse_iso_dt(incident_report.get("detected_at")) or datetime.now(tz=UTC)
    completed_at = _parse_iso_dt(incident_report.get("investigation_completed_at"))

    # ── Agent: CHRONOS software ───────────────────────────────────────────────
    agent = d.agent(
        "chronos:agent_chronos",
        {
            PROV_TYPE: "prov:SoftwareAgent",
            "chronos:version": settings.version,
            "chronos:service": "chronos-rca",
        },
    )

    # ── Activity: the investigation run ───────────────────────────────────────
    activity = d.activity(
        f"chronos:investigation_{_safe_id(incident_id)}",
        startTime=detected_at,
        endTime=completed_at,
        other_attributes={
            PROV_TYPE: "chronos:RCAInvestigation",
            "chronos:incident_id": incident_id,
        },
    )
    d.wasAssociatedWith(activity, agent)

    # ── Entity: the affected data asset ───────────────────────────────────────
    data_entity = d.entity(
        f"chronos:asset_{_safe_id(entity_fqn)}",
        {
            PROV_TYPE: "chronos:DataAsset",
            "chronos:fqn": entity_fqn,
            "chronos:test_name": incident_report.get("test_name", ""),
        },
    )
    d.used(activity, data_entity, time=detected_at)

    # ── Entity: the incident report (output of investigation) ─────────────────
    report_entity = d.entity(
        f"chronos:report_{_safe_id(incident_id)}",
        {
            PROV_TYPE: "chronos:IncidentReport",
            "chronos:incident_id": incident_id,
            "chronos:root_cause_category": incident_report.get("root_cause_category", "UNKNOWN"),
            "chronos:confidence": str(incident_report.get("confidence", 0.0)),
            "chronos:business_impact": incident_report.get("business_impact", "medium"),
            "chronos:probable_root_cause": incident_report.get("probable_root_cause", "")[
                :200
            ],  # Truncate for PROV attribute limits
        },
    )
    d.wasGeneratedBy(report_entity, activity, time=completed_at)
    d.wasAttributedTo(report_entity, agent)
    d.wasDerivedFrom(report_entity, data_entity)

    # ── Entities: evidence chain ──────────────────────────────────────────────
    for i, evidence in enumerate(incident_report.get("evidence_chain", [])[:10]):
        ev_entity = d.entity(
            f"chronos:evidence_{_safe_id(incident_id)}_{i}",
            {
                PROV_TYPE: "chronos:Evidence",
                "chronos:source": evidence.get("source", "unknown"),
                "chronos:description": str(evidence.get("description", ""))[:200],
                "chronos:confidence": str(evidence.get("confidence", 0.5)),
            },
        )
        ev_ts = _parse_iso_dt(
            str(evidence.get("timestamp", "")) if evidence.get("timestamp") else None
        )
        d.used(activity, ev_entity, time=ev_ts)
        d.wasDerivedFrom(report_entity, ev_entity)

    # ── Downstream asset entities (for impact provenance) ─────────────────────
    for j, asset in enumerate(incident_report.get("affected_downstream", [])[:5]):
        asset_fqn = asset.get("fqn", f"unknown_{j}")
        downstream_entity = d.entity(
            f"chronos:downstream_{_safe_id(incident_id)}_{j}",
            {
                PROV_TYPE: "chronos:DownstreamAsset",
                "chronos:fqn": asset_fqn,
                "chronos:tier": asset.get("tier", ""),
            },
        )
        d.wasDerivedFrom(downstream_entity, data_entity)

    return d


def _stub_provenance(incident_report: dict) -> ProvDocument:
    """Return a minimal valid PROV-O document when full generation fails."""
    d = ProvDocument()
    d.set_default_namespace(CHRONOS_NS)
    d.add_namespace("prov", PROV_NS)
    d.add_namespace("chronos", CHRONOS_NS)

    incident_id = incident_report.get("incident_id", "unknown")
    agent = d.agent("chronos:agent_chronos", {PROV_TYPE: "prov:SoftwareAgent"})
    activity = d.activity(
        f"chronos:investigation_{_safe_id(incident_id)}",
        other_attributes={PROV_TYPE: "chronos:RCAInvestigation"},
    )
    d.wasAssociatedWith(activity, agent)
    stub_entity = d.entity(
        f"chronos:stub_{_safe_id(incident_id)}",
        {
            PROV_TYPE: "chronos:IncidentReport",
            "chronos:incident_id": incident_id,
            "chronos:note": "Provenance generation failed; this is a minimal stub.",
        },
    )
    d.wasGeneratedBy(stub_entity, activity)
    # prov:wasInvalidatedBy signals downstream consumers that this document is incomplete.
    d.wasInvalidatedBy(stub_entity, activity)
    return d


def safe_generate_provenance(incident_report: dict) -> ProvDocument:
    """Generate PROV-O document, falling back to a stub on any failure."""
    try:
        return generate_provenance(incident_report)
    except Exception as exc:
        logger.error(
            "generate_provenance failed for incident %s (%s): %s — returning stub",
            incident_report.get("incident_id"),
            type(exc).__name__,
            exc,
        )
        return _stub_provenance(incident_report)
