"""
Graphify context enrichment.

Reads GRAPH_REPORT.md generated by the Graphify tool and extracts relevant
sections for the affected entity to enrich the RCA synthesis context.
"""

from __future__ import annotations

from pathlib import Path

GRAPH_REPORT_PATH = Path(__file__).parent.parent.parent / "GRAPH_REPORT.md"

_MAX_CHARS = 2000
_CONTEXT_LINES_BEFORE = 2
_CONTEXT_LINES_AFTER = 5
_MAX_OUTPUT_LINES = 100


def get_graphify_context(entity_name: str = "") -> str:
    """
    Read GRAPH_REPORT.md and return relevant context.

    If ``entity_name`` is provided, extracts only sections that mention the
    entity (case-insensitive), returning up to ``_MAX_OUTPUT_LINES`` lines.

    If no entity name is given, returns the first ``_MAX_CHARS`` characters of
    the full report.

    Returns an empty string if GRAPH_REPORT.md does not exist.
    """
    if not GRAPH_REPORT_PATH.exists():
        return ""

    content = GRAPH_REPORT_PATH.read_text(encoding="utf-8")

    if not entity_name:
        return content[:_MAX_CHARS]

    lines = content.split("\n")
    relevant: list[str] = []
    entity_lower = entity_name.lower()

    for i, line in enumerate(lines):
        if entity_lower in line.lower():
            start = max(0, i - _CONTEXT_LINES_BEFORE)
            end = min(len(lines), i + _CONTEXT_LINES_AFTER + 1)
            chunk = lines[start:end]
            relevant.extend(chunk)
            relevant.append("---")

            if len(relevant) >= _MAX_OUTPUT_LINES:
                break

    return "\n".join(relevant[:_MAX_OUTPUT_LINES]) if relevant else ""
